### ISSUE TITLE
Uncaught exception leads to crashing server

### ISSUE THREAD

**Issue by beevelop** [plouc/mozaik-ext-travis#3]
| item | info | notes |
| --- | --- | --- |
| **node** version | v6.3.0 | _output from `node --version`_ |
| **npm** version | 3.10.3 | _output from `npm --version`_ |
| **mozaik-ext-travis** version | 1.1.0 | _available in project's `package.json`_ |
| **mozaik** version | 1.4.4 | _available in project's `package.json`_ |
| **mozaik-demo** | master | _version of the demo used_ |
## Expected behavior

Handle Travis errors and exceptions properly (instead of crashing the server).
## Actual behavior

```
code = "ECONNRESET"
message = "socket hang up"
```

leads to

```
/mozaik-demo/node_modules/mozaik-ext-travis/src/client.js:84
                res.builds.forEach(function (build) {
                   ^

TypeError: Cannot read property 'builds' of undefined
    at client.js:59:17
    at /mozaik-demo/node_modules/travis-ci/lib/travis-ci.js:51:21
```
## Steps to reproduce
1. Launch the mozaik-demo
2. Join a crappy public WiFi

**Comment by perry-mitchell** [comment]
I had this as well, which also crashed my server after some 20-24 hours:

```
/mozaik/node_modules/mozaik-ext-travis/src/client.js:84       
                res.builds.forEach(function (build) {
                   ^                                                            

TypeError: Cannot read property 'builds' of undefined                           
    at client.js:59:17
    at /mozaik/node_modules/travis-ci/lib/travis-ci.js:51:21  
    at Request._callback (/mozaik/node_modules/travis-ci/lib/travis-http.js:41:20)                                                            
    at self.callback (/mozaik/node_modules/travis-ci/node_modules/request/index.js:148:22)                                                    
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)                                           
    at ClientRequest.self.clientErrorHandler (/mozaik/node_modules/travis-ci/node_modules/request/index.js:257:10)                            
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)                                     
    at TLSSocket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)                                                
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1015:8)                                           
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
